### ISSUE TITLE
some errors in detection set up

### ISSUE THREAD

**Issue by zaqai** [sunsmarterjie/iTPN#6]
Hi Yunjie, I follow your readme to set up detection env. But I met a lot of problems. Could you please check it again?

Here is some confusing points,
1. the readme in main repo said it using py38 while in det folder, it is py37
2. the readme in det installs mmcv-full==1.5.1. But [Swin-Transformer-Object-Detection](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/blob/master/mmdet/__init__.py) restricts the version less than 1.4.0
3. After installing mmdet in Swin-Transformer-Object-Detection, I will get the simillar error `cannot import name 'init_random_seed' from 'mmdet.apis'` .etc
4. So I chose install mmdet in open-mmlab/mmdetection, and copy mmcv_custome form Swin-Transformer-Object-Detection to mmdetection. I can run train.py and generate corresponding config file in work_dir, But I met another error.
> Traceback (most recent call last):
  File "det/tools/train.py", line 237, in <module>
    main()
  File "det/tools/train.py", line 210, in main
    test_cfg=cfg.get('test_cfg'))
  File "/home/ZhouQi/repo/mmdetection/mmdet/models/builder.py", line 59, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/ZhouQi/anaconda3/envs/itpn37/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/ZhouQi/anaconda3/envs/itpn37/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/ZhouQi/anaconda3/envs/itpn37/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
NameError: MaskRCNN: iTPN_pixel: name 'init_cfg' is not defined

I have struggled with env set up a few days. Hope you can help me Or provide more details about env set up.

**Comment by sunsmarterjie** [comment]
wechat: 18843114102



---- Replied Message ----
| From | Qi ***@***.***> |
| Date | 04/11/2023 18:31 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [sunsmarterjie/iTPN] some errors in detection set up (Issue #6) |

Hi Yunjie, I follow your readme to set up detection env. But I met a lot of problems. Could you please check it again?

Here is some confusing points,

the readme in main repo said it using py38 while in det folder, it is py37
the readme in det installs mmcv-full==1.5.1. But Swin-Transformer-Object-Detection restricts the version less than 1.4.0
After installing mmdet in Swin-Transformer-Object-Detection, I will get the simillar error cannot import name 'init_random_seed' from 'mmdet.apis' .etc
So I chose install mmdet in open-mmlab/mmdetection, and copy mmcv_custome form Swin-Transformer-Object-Detection to mmdetection. I can run train.py and generate corresponding config file in work_dir, But I met another error.

Traceback (most recent call last):
File "det/tools/train.py", line 237, in
main()
File "det/tools/train.py", line 210, in main
test_cfg=cfg.get('test_cfg'))
File "/home/ZhouQi/repo/mmdetection/mmdet/models/builder.py", line 59, in build_detector
cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
File "/home/ZhouQi/anaconda3/envs/itpn37/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
return self.build_func(*args, **kwargs, registry=self)
File "/home/ZhouQi/anaconda3/envs/itpn37/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
return build_from_cfg(cfg, registry, default_args)
File "/home/ZhouQi/anaconda3/envs/itpn37/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
raise type(e)(f'{obj_cls.name}: {e}')
NameError: MaskRCNN: iTPN_pixel: name 'init_cfg' is not defined

I have struggled with env set up a few days. Hope you can help me Or provide more details about env set up.
